# Generated by Django 4.1 on 2022-12-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=100)),
                ('email_Id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('conf_pass', models.CharField(max_length=100)),
                ('Contact_no', models.IntegerField()),
            ],
            options={
                'db_table': 'Customer',
                'ordering': ['Customer_Id'],
            },
        ),
    ]
